# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20180718_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaiable',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
